version: '3'
services:
  ssh-contasiner:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    ports: 
      - 2222:22
    volumes:
      - /home/anchit/Desktop/Study/containerization/docker-volume:/home